language:
# linux
- cpp

# osx
# - objective-c

env:
# linux
- build=release
- build=debug
- build=cli

install:
# linux
- if [[ "$build" != "cli" ]]; then sudo add-apt-repository -y ppa:fransschreuder1/usbpicprog-stable; fi
- sudo apt-get -qq update
- sudo apt-get -qq install git cmake gettext libwayland-dev libsdl1.2-dev libxrandr-dev libxext-dev libglew-dev libavcodec-dev libavformat-dev libsoil-dev libsfml-dev libopenal-dev libao-dev libasound2-dev libpulse-dev libportaudio-dev libsoundtouch-dev libbluetooth-dev libreadline-dev libswscale-dev liblzo2-dev
- if [[ "$build" != "cli" ]]; then sudo apt-get -qq install wx2.9-headers libwxbase2.9-dev libwxgtk2.9-dev libgtk-3-dev; fi
- export MAKEFLAGS="-j $((`nproc` / 2))"

# osx
# - brew update
# - brew install cmake
# - export MAKEFLAGS="-j 4"

script:
- if [[ "$build" == "release" ]]; then cmake . && make; fi
- if [[ "$build" == "debug" ]]; then cmake -DCMAKE_BUILD_TYPE=Debug . && make; fi
- if [[ "$build" == "cli" ]]; then cmake -DDISABLE_WX=ON . && make; fi
